In [1]:
import numpy as np

In [2]:
# 2-D Array
arr2d = np.array([
                  [1, 2, 3],
                  [4, 5, 6]
])

In [3]:
arr2d1 = np.array([[1,2,3],[4,5,6]])

In [4]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2d.ndim

2

In [6]:
arr2d.shape

(2, 3)

In [7]:
arr2d.size

6

In [8]:
# 3-D Array
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10, 11, 12]
                  ]
])

In [9]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d.shape

(2, 2, 3)

In [11]:
arr3d.size

12

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
120 * np.ones((2, 3))

array([[120., 120., 120.],
       [120., 120., 120.]])

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Random
np.random.randn(2, 3)

array([[-0.96691392, -1.27545665,  0.25261275],
       [ 0.49777325, -2.49217532,  0.82100188]])

In [16]:
np.random.randint(0, 100, (2, 3))

array([[72, 35, 50],
       [84, 23, 17]])

In [17]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [19]:
str_arr = np.array(['1.1', '2.2', '3.3', '4.4'])

In [20]:
str_arr

array(['1.1', '2.2', '3.3', '4.4'], dtype='<U3')

In [21]:
# conversion
arr = np.array(str_arr, dtype='float')

In [22]:
arr

array([1.1, 2.2, 3.3, 4.4])

In [23]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)

In [24]:
arr1

array([[0.18610541, 0.73097051, 0.89250686, 0.22635812],
       [0.02770091, 0.93299291, 0.64609432, 0.16443362],
       [0.71749039, 0.13113233, 0.0248161 , 0.3211739 ]])

In [25]:
arr2

array([[0.54297658, 0.63036514, 0.96111392, 0.98548191],
       [0.42950039, 0.51936888, 0.89976522, 0.98317372],
       [0.93838606, 0.39840461, 0.14531065, 0.67038404]])

In [26]:
arr1+arr2

array([[0.72908199, 1.36133565, 1.85362077, 1.21184003],
       [0.4572013 , 1.45236179, 1.54585954, 1.14760734],
       [1.65587645, 0.52953693, 0.17012675, 0.99155793]])

In [27]:
arr1-arr2

array([[-0.35687117,  0.10060537, -0.06860706, -0.75912379],
       [-0.40179948,  0.41362403, -0.2536709 , -0.8187401 ],
       [-0.22089566, -0.26727228, -0.12049455, -0.34921014]])

In [28]:
arr1/arr2

array([[0.34275034, 1.15959857, 0.92861714, 0.22969282],
       [0.06449565, 1.79639741, 0.7180699 , 0.16724778],
       [0.76460044, 0.3291436 , 0.17077964, 0.47908941]])

In [29]:
np.exp(arr1)

array([[1.20454922, 2.07709548, 2.44124183, 1.25402468],
       [1.02808814, 2.54210609, 1.90807394, 1.17872532],
       [2.04928386, 1.14011864, 1.02512658, 1.37874532]])

In [30]:
np.log(arr1)

array([[-1.68144206, -0.31338216, -0.11372108, -1.48563692],
       [-3.58629014, -0.06935768, -0.43680977, -1.80524833],
       [-0.33199572, -2.03154833, -3.69626264, -1.13577257]])

In [31]:
np.log(np.exp(arr1))

array([[0.18610541, 0.73097051, 0.89250686, 0.22635812],
       [0.02770091, 0.93299291, 0.64609432, 0.16443362],
       [0.71749039, 0.13113233, 0.0248161 , 0.3211739 ]])

In [32]:
np.sqrt(arr1)

array([[0.43139936, 0.85496814, 0.94472581, 0.47577108],
       [0.16643589, 0.96591558, 0.80379993, 0.40550415],
       [0.84704805, 0.36212198, 0.15753127, 0.56672206]])

In [38]:
cric_data = np.loadtxt("cric_data.tsv")

ValueError: could not convert string to float: 'Sachin'

In [39]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)

In [40]:
cric_data.shape

(225, 4)

In [41]:
cric_data = cric_data[:, [1, 2, 3]]

In [42]:
cric_data.shape

(225, 3)

In [43]:
sachin = cric_data[:, 0]
rahul = cric_data[:, 1]
india = cric_data[:, 2]

In [44]:
sachin.shape

(225,)

In [45]:
def stats(col):
  print('Mean', np.mean(col))
  print('Median', np.median(col))

In [46]:
stats(sachin)

Mean 39.87555555555556
Median 27.0


In [47]:

stats(rahul)

Mean 32.062222222222225
Median 22.0


In [48]:
np.mean(cric_data, axis=0)

array([ 39.87555556,  32.06222222, 220.79555556])

In [49]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [50]:
sachin25 = sachin.reshape(9, 25)

In [51]:
sachin25.shape

(9, 25)

In [52]:
np.mean(sachin25, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [53]:
sachin >= 100

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [54]:
sachin[sachin >= 100]

array([100., 104., 138., 141., 186., 146., 141., 123., 120., 122., 100.,
       152., 105., 122., 100., 117., 141., 139., 114., 127., 110., 146.,
       101., 140., 113., 102.])

In [55]:
np.mean(sachin[sachin >= 100])

125.0

In [56]:
rahul <= 10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
        True, False,  True, False,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False, False, False, False,
        True,  True,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True, False, False, False, False,  True, False, False, False,
        True, False,

In [57]:
sachin[rahul <= 10]

array([ 37.,  14.,   4.,   0.,  62.,  38.,  65.,   0.,  48.,  62.,  27.,
        27.,  51.,  18.,  65.,  28.,   2.,  54.,   4.,  14., 100.,  57.,
         0.,   5.,   0.,  30.,  83.,  93.,   0., 152.,   0.,   1.,  53.,
         0.,  81.,  78., 122.,   9.,  13.,  36.,  29.,  12.,  34., 100.,
        44.,  82.,   0.,   6.,  49.,  64.,  43.,  72.,   3.,  44.,  47.,
        17.,  35.,  88.,   0.,  33., 110., 146.,   7.,  11.,  94.,  55.,
         0.,  28.,   2.,  27.,  40.])

In [58]:
np.mean(sachin[rahul <= 10])

40.2112676056338